config/routes.rb
Rails.application.routes.draw do

  root 'dashboards#visites_preventive'

  get 'dashboards/tableau_board'
  get 'dashboards/visites_preventive'

  resources :intervenants
  resources :clients
  resources :type_contrats
  resources :qualites
  resources :regions
  resources :specialites

  devise_for :users, :controllers => { registrations: 'registrations' },
      :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  get 'print_contrats' => 'contrats#print_contrats'
  get 'print_visites' => 'contrats#print_visites'
  get 'apercu' => 'contrats#apercu'

  resources :contrats do
    collection {
      post :update_main_oeuvre
      post :update_piece_rechange
    }
    resources :visites
    get 'index2' => 'visites#index2'
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :region

  default_scope -> { order(raison_social: :asc) }

  def raison_social
    read_attribute(:raison_social).to_s.upcase
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_url, notice: 'Client a été créé avec succès.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to clients_url, notice: 'Client  a été mis à jour avec succès.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client a été supprimé avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:code, :raison_social, :adresse, :telephone, :fax, :contact, :email, :region_id)
    end
end

app/views/clients/_form.html.erb
<% content_for :box_width, "col-md-8" %>


<%= form_for(@client,:html => { :class => 'from-inline'}) do |f| %>
  <div class="box-body">

    <div class="row">
      <div class="form-group">
        <%= f.label :code, class: 'col-sm-2 control-label required' %>
        <div class="col-sm-4">
          <%= f.text_field :code, :class => 'form-control', placeholder: :code, :required => true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :raison_social, class: 'col-sm-2 control-label required' %>
        <div class="col-sm-4">
          <%= f.text_field :raison_social, :class => 'form-control uppercase-input', placeholder: :raison_social, :required => true %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <%= f.label 'Téléphone', class: 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.telephone_field :telephone, :class => 'form-control', placeholder: :telephone %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :fax, class: 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.telephone_field :fax, :class => 'form-control', placeholder: :fax%>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <%= f.label :contact, class: 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.text_field :contact, :class => 'form-control', placeholder: :contact %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :email, class: 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.text_field :email, :class => 'form-control', placeholder: :email %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <%= f.label 'Région', class: 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.collection_select(:region_id, Region.all, :id, :nom, {}, { :class => 'select2 select2-custom' })%>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :adresse, class: 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.text_area :adresse, :class => 'form-control', placeholder: :adresse %>
        </div>
      </div>
    </div>


  </div>


  <div class="box-footer">
    <button type="submit" class="btn btn-primary pull-right">
      <i class="fa fa-floppy-o" aria-hidden="true"></i> Valider
    </button>
    <a href="<%= clients_url %>" class="btn btn-default pull-right">
      <i class="fa fa-times" aria-hidden="true"></i> Annuler
    </a>
  </div>
<% end %>

app/views/clients/edit.html.erb
<% content_for :page_title do %>
  Edition Client
<% end %>

<%= render 'form' %>

app/views/clients/index.html.erb
<% content_for :box_width, "col-md-12" %>

<% content_for :page_title do %>
  Liste Clients
<% end %>

<div class="box-body">
  <table class="sortable datatable table table-hover table-condensed table-striped">
    <thead>
      <tr>
        <th>Code</th>
        <th>Raison Social</th>
        <th>Téléphone</th>
        <th>Contact</th>
        <th>Email</th>
        <th>Région</th>
        <td class="actions no-sort"></td>
      </tr>
    </thead>

    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><%= client.code %></td>
          <td><%= client.raison_social %></td>
          <td><%= client.telephone %></td>
          <td><%= client.contact %></td>
          <td><%= client.email %></td>
          <td><%= client.region.nom if client.region %></td>
          <td class="actions">
            <%= link_to edit_client_path(client) do %>
              <%= fa_stacked_icon "pencil inverse", base: "circle", class: "edit fa-1x" %>
            <% end %>

            <%= link_to client, method: :delete, data: { confirm: 'Voulez-vous vraiment supprimer cet élément?' } do %>
              <%= fa_stacked_icon "trash inverse", base: "circle", class: "delete fa-1x" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


  <%= link_to new_client_path, class: 'btn btn-primary' do %>
    <%= fa_icon 'plus' %> Nouveau Client
  <% end %>
</div>

app/views/clients/new.html.erb
<% content_for :page_title do %>
  Nouveau Client
<% end %>

<%# content_for :box_width, "col-md-6" %>


<%= render 'form' %>