config/routes.rb
Rails.application.routes.draw do

  root 'dashboards#visites_preventive'

  get 'dashboards/tableau_board'
  get 'dashboards/visites_preventive'

  resources :intervenants
  resources :clients
  resources :type_contrats
  resources :qualites
  resources :regions
  resources :specialites

  devise_for :users, :controllers => { registrations: 'registrations' },
      :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  get 'print_contrats' => 'contrats#print_contrats'
  get 'print_visites' => 'contrats#print_visites'
  get 'apercu' => 'contrats#apercu'

  resources :contrats do
    collection {
      post :update_main_oeuvre
      post :update_piece_rechange
    }
    resources :visites
    get 'index2' => 'visites#index2'
  end

end

app/models/contrat.rb
class Contrat < ActiveRecord::Base
  belongs_to :type_contrat
  belongs_to :client
  belongs_to :intervenant
  has_many :visites, dependent: :destroy

  accepts_nested_attributes_for :visites,
                                allow_destroy: true,
                                reject_if: proc { |attributes| attributes['date'].blank? }

  # default_scope -> { where("numero like '%A%'") }
  default_scope -> { order(numero: :asc) }
  scope :print, -> { includes(:client).order('clients.raison_social ASC') }

  scope :terminate_5_weeks_from_now, ->{ where('date_fin >= ? AND date_fin <= ? ', Date.today, 5.weeks.from_now)}

  validates :numero, :presence => true

  def date_creation
    I18n.l read_attribute(:date_creation) if read_attribute(:date_creation)
  end

  def date_debut
    I18n.l read_attribute(:date_debut) if read_attribute(:date_debut)
  end

  def date_fin
    I18n.l read_attribute(:date_fin) if read_attribute(:date_fin)
  end

  def resile_presentation
    resile ? "Oui" : "Non"
  end

  def main_oeuvre_presentation
    main_oeuvre ? "Oui" : "Non"
  end

  def piece_rechange_presentation
    piece_rechange ? "Oui" : "Non"
  end

  def nombre_incidents
    read_attribute(:nombre_incidents) || 0
  end

  def nombre_visites
    read_attribute(:nombre_visites) || 0
  end

  def visite_of_a_month(month)
    visite = visites.where("strftime('%m', visites.date) = ?", month).first
    visite_color = ''
    visite_color = visite.color.tr('#', '') if visite != nil and visite.color != nil
    if (visite_color != '' and visite_color != 'FFFFFF')
      {:content => visite.nil? ? "" : visite.date, :background_color => visite_color, :text_color => 'FFFFFF'}
    else
      visite.nil? ? "" : visite.date
    end
  end

  def isTerminated
    read_attribute(:date_fin) < Date.today ? true : false
  end

  def contrat_line
    [
        client.raison_social, intervenant.nom, client.contact,
        visite_of_a_month("01"), visite_of_a_month("02"), visite_of_a_month("03"), visite_of_a_month("04"),
        visite_of_a_month("05"), visite_of_a_month("06"), visite_of_a_month("07"), visite_of_a_month("08"),
        visite_of_a_month("09"), visite_of_a_month("10"), visite_of_a_month("11"), visite_of_a_month("12")
    ]
  end

  # def contrat_line
  #   [contrat.client.raison_social, contrat.intervenant.nom, contrat.client.contact,
  #    # "", "", "", "", "", "",
  #    # "", "", "", "", "", ""]
  #    #
  #    contrat.visite_of_a_month("01"), contrat.visite_of_a_month("02"), contrat.visite_of_a_month("03"), contrat.visite_of_a_month("04"),
  #    contrat.visite_of_a_month("05"), contrat.visite_of_a_month("06"), contrat.visite_of_a_month("07"), contrat.visite_of_a_month("08"),
  #    contrat.visite_of_a_month("09"), contrat.visite_of_a_month("10"), contrat.visite_of_a_month("11"), contrat.visite_of_a_month("12")]
  # end

end

app/controllers/contrats_controller.rb
class ContratsController < ApplicationController
  before_action :set_contrat, only: [:show, :edit, :update, :destroy]
  before_action :set_contrats, only: [:index, :print_visites, :apercu]

  # GET /contrats
  # GET /contrats.json
  def index

  end

  # GET /print_contrats
  def print_contrats
    @contrats = Contrat.print
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ContratsPDF.new(@contrats, view_context)
        send_data pdf.render, filename: "contrats.pdf",
                  type: "application/pdf",
                  disposition: "inline"
      end
    end
  end

  # GET /print_visites
  def print_visites
    respond_to do |format|
      format.html
      format.pdf do
        pdf = VisitesPDF.new(@contrats, view_context)
        send_data pdf.render, filename: "visites.pdf",
                  type: "application/pdf",
                  disposition: "inline"
      end
    end
  end

  # GET /contrats
  def apercu
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ContratsPDF.new(@contrats, view_context)
        send_data pdf.render, filename: "contrats.pdf",
                  type: "application/pdf",
                  disposition: "inline"
      end
    end
  end

  # GET /contrats/1
  # GET /contrats/1.json
  def show
  end

  # GET /contrats/new
  def new
    @contrat = Contrat.new
  end

  # GET /contrats/1/edit
  def edit
  end

  # POST /contrats
  # POST /contrats.json
  def create
    @contrat = Contrat.new(contrat_params)

    respond_to do |format|
      if @contrat.save
        format.html { redirect_to contrats_url, notice: 'Contrat a été créé avec succès.' }
        format.json { render :show, status: :created, location: @contrat }
      else
        format.html { render :new }
        format.json { render json: @contrat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contrats/1
  # PATCH/PUT /contrats/1.json
  def update
    respond_to do |format|
      if @contrat.update(contrat_params)
        format.html { redirect_to contrats_url, notice: 'Contrat  a été mis à jour avec succès.' }
        format.json { render :show, status: :ok, location: @contrat }
      else
        format.html { render :edit }
        format.json { render json: @contrat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contrats/1
  # DELETE /contrats/1.json
  def destroy
    @contrat.destroy
    respond_to do |format|
      format.html { redirect_to contrats_url, notice: 'Contrat a été supprimé avec succès.' }
      format.json { head :no_content }
    end
  end

  def update_main_oeuvre
    model_class.where(:id => params[:id]).update_all(:main_oeuvre => params[:main_oeuvre] == "true" ? '1' : '0')

    respond_to do |format|
      format.js  { render :text => 'Ok' }
    end
  end

  def update_piece_rechange
    model_class.where(:id => params[:id]).update_all(:piece_rechange => params[:piece_rechange] == "true" ? '1' : '0')

    respond_to do |format|
      format.js  { render :text => 'Ok' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contrat
      @contrat = Contrat.find(params[:id])
    end

    def set_contrats
      @contrats = Contrat.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contrat_params
      params.require(:contrat).permit!
    end
end

app/views/contrats/_contrats_sidebar.html.erb
<div class="col-md-2">
  <div class="box box-primary">
    <div class="box-body">
      <nav class="right_sidebar">
        <br/>
        <ul class="nav nav-pills nav-stacked">
          <li>
            <%= active_link_to contrats_path do %>
              <%= fa_icon 'sliders' %> Contrats
            <% end %>
          </li>
          <li>
            <%= active_link_to apercu_path do %>
              <%= fa_icon 'eye' %> Aperçu
            <% end %>
          </li>
          <li>
            <%= active_link_to print_contrats_path(format: 'pdf'), target: "_blank" do %>
              <%= fa_icon 'print' %> Imprimer
            <% end %>
          </li>
          <li>
            <%= active_link_to print_visites_path(format: 'pdf'), target: "_blank" do %>
              <%= fa_icon 'calendar' %> Visites
            <% end %>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/contrats/_form.html.erb
<% content_for :box_width, "col-md-9" %>


<%= form_for(@contrat,:html => { :class => 'from-inline'}) do |f| %>
  <div class="box-body">

    <div class="row">
      <div class="form-group">
        <%= f.label :numero, :class => 'col-sm-2 control-label required' %>
        <div class="col-sm-4">
          <%= f.text_field :numero, :class => 'form-control', placeholder: :numero, :required => true %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label 'Client', :class => 'col-sm-2 control-label required' %>
        <div class="col-sm-4">
          <%= f.collection_select(:client_id, Client.all, :id, :raison_social, {:selected => @contrat.client_id, :include_blank => true}, { :class => 'select2 select2-custom', :required => true })%>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <%= f.label 'Type Contrat', :class => 'col-sm-2 control-label required' %>
        <div class="col-sm-4">
          <%= f.collection_select(:type_contrat_id, TypeContrat.all, :id, :nom, {:selected => @contrat.type_contrat_id, :include_blank => true}, { :class => 'select2 select2-custom', :required => true })%>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Intervenant', :class => 'col-sm-2 control-label required' %>
        <div class="col-sm-4">
          <%= f.collection_select(:intervenant_id, Intervenant.all, :id, :nom, {:selected => @contrat.intervenant_id, :include_blank => true}, { :class => 'select2 select2-custom', :required => true })%>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <%= f.label "Date Creation", :class => 'col-sm-2 control-label required' %>
        <div class="col-sm-4">
          <div class="input-group date">
            <%= f.text_field :date_creation, :class => 'form-control pull-right datepicker', placeholder: 'Date Creation', :required => true %>
            <div class="input-group-addon">
              <i class="fa fa-calendar"></i>
            </div>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :nombre_incidents, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.number_field :nombre_incidents, :class => 'form-control'  %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <%= f.label "Date Debut", :class => 'col-sm-2 control-label required' %>
        <div class="col-sm-4">
          <div class="input-group date">
            <%= f.text_field :date_debut, :class => 'form-control pull-right datepicker', placeholder: 'Date Debut', :required => true %>
            <div class="input-group-addon">
              <i class="fa fa-calendar"></i>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :nombre_visites, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.number_field :nombre_visites, :class => 'form-control'   %>
        </div>
      </div>
    </div>

      <div class="row">
        <div class="form-group">
          <%= f.label "Date Fin", :class => 'col-sm-2 control-label required' %>
          <div class="col-sm-4">
            <div class="input-group date">
              <%= f.text_field :date_fin, :class => 'form-control pull-right datepicker', placeholder: 'Date Fin' , :required => true%>
              <div class="input-group-addon">
                <i class="fa fa-calendar"></i>
              </div>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :montant, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-4">
            <%= f.number_field :montant, :class => 'form-control', :step => '0.01' %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="form-group">
          <%= f.label :main_oeuvre, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-4">
            <%= f.check_box :main_oeuvre, class: 'icheck', 'data-skin' => "square"  %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :resile, :class => 'col-sm-2 control-label' %>
          <div class="col-sm-4">
            <%= f.check_box :resile, class: 'icheck', 'data-skin' => "square"  %>
          </div>
        </div>
      </div>

    <div class="row">

      <div class="form-group">
        <%= f.label :piece_rechange, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.check_box :piece_rechange, class: 'icheck', 'data-skin' => "square"  %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :cause_resile, :class => 'col-sm-2 control-label' %>
        <div class="col-sm-4">
          <%= f.text_area :cause_resile, :class => 'form-control', placeholder: :cause_resile, :readonly => !f.object.resile %>
        </div>
      </div>
    </div>


  </div>


  <div class="box-footer">
    <button type="submit" class="btn btn-primary pull-right">
      <i class="fa fa-floppy-o" aria-hidden="true"></i> Valider
    </button>
    <a href="<%= contrats_url %>" class="btn btn-default pull-right">
      <i class="fa fa-times" aria-hidden="true"></i> Annuler
    </a>
  </div>
<% end %>

app/views/contrats/apercu.html.erb
<% content_for :box_width, "col-md-12" %>
<% content_for :page_title do %>
  Liste contrats
<% end %>


<div class="box-body apercu-contrats">
  <table class="ddatatable table table-striped table-bordered">
    <thead>
      <tr>
        <th>Contrat</th>
        <th>Client</th>
        <th>Date Création</th>
        <th>Date Début</th>
        <th>Date Fin</th>
        <th>Type Contrat</th>
        <th>Intervenant</th>
        <th>Main Oeuvre</th>
        <th>Pièces</th>
        <th>Nbr Incidents</th>
        <th>Nbr Visites</th>
        <th>Résilier</th>
        <th>Montant</th>
      </tr>
    </thead>

    <tbody>
      <% @contrats.each do |contrat| %>
        <tr style="<%= 'background-color: #FEFD9F' if contrat.resile %> <%= 'background-color: #FBCCD4' if contrat.isTerminated and !contrat.resile %>">
          <td><%= contrat.numero %></td>
          <td><%= contrat.client.raison_social if contrat.client %></td>
          <td><%= contrat.date_creation %></td>
          <td><%= contrat.date_debut %></td>
          <td style="<%= 'font-weight:bold' if contrat.isTerminated or contrat.resile %>"><%= contrat.date_fin %></td>
          <td><%= truncate(contrat.type_contrat.nom, :length => 15) %></td>
          <td><%= contrat.intervenant.nom %></td>
          <td style="text-align: center;">
            <%= check_box_tag 'contrat[main_oeuvre]', contrat.main_oeuvre, contrat.main_oeuvre, class: 'iicheck', 'data-skin' => "square",
                              onchange: "$(this).data('params', 'main_oeuvre=' + this.checked)",
                              data: {
                                      remote: true,
                                      url: url_for(action: :update_main_oeuvre, id: contrat.id),
                                      method: "POST"
                              }   %>
          </td>
              <td style="text-align: center;">
            <%= check_box_tag 'contrat[piece_rechange]', contrat.piece_rechange, contrat.piece_rechange, class: 'iicheck', 'data-skin' => "square",
                              onchange: "$(this).data('params', 'piece_rechange=' + this.checked)",
                              data: {
                                      remote: true,
                                      url: url_for(action: :update_piece_rechange, id: contrat.id),
                                      method: "POST"
                              }   %>
          </td>
              <td style="text-align: center;"><%= contrat.nombre_incidents %></td>
              <td style="text-align: center;"><%= contrat.nombre_visites %></td>
          <td style="text-align: center;<%= 'font-weight:bold' if contrat.resile %>">
            <%= contrat.resile_presentation %>
            <%#= check_box_tag 'contrat[resile]', contrat.resile, contrat.resile, class: 'iicheck', 'data-skin' => "square",
                              onchange: "$(this).data('params', 'resile=' + this.checked)",
                              data: {
                                      remote: true,
                                      url: url_for(action: :update_resile, id: contrat.id),
                                      method: "POST"
                              }   %>
            <%#= check_box_tag 'contrat[resile]', contrat.resile, contrat.resile, class: 'iicheck', 'data-skin' => "square"  %>
          </td>
          <td style="text-align: right;"><%= number_to_currency(contrat.montant) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/contrats/edit.html.erb
<% content_for :page_title do %>
  Edition Contrat
<% end %>

<%= render 'form' %>

app/views/contrats/index.html.erb
<% content_for :box_width, "col-md-12" %>
<% content_for :page_title do %>
  Liste contrats
<% end %>

<div class="box-body">
  <table class="sortable datatable table table-hover table-condensed table-striped">
    <thead>
      <tr>
        <th>N˚ Contrat</th>
        <th>Client</th>
        <th>Date Début</th>
        <th>Date Fin</th>
        <th>Type Contrat</th>
        <th>Montant</th>
        <td class="actions no-sort"></td>
      </tr>
    </thead>

    <tbody>
      <% @contrats.each do |contrat| %>
        <tr>
          <td><%= contrat.numero %></td>
          <td><%= contrat.client.raison_social if contrat.client %></td>
          <td><%= contrat.date_debut %></td>
          <td><%= contrat.date_fin %></td>
          <td><%= contrat.type_contrat.nom if contrat.type_contrat %></td>
          <td style="text-align: right;;"><%= number_to_currency(contrat.montant) %></td>
          <td class="actions">

            <%= link_to contrat_visites_path(contrat) do %>
              <%= fa_stacked_icon "calendar-check-o inverse", base: "circle", class: "visit fa-1x" %>
            <% end %>

            <%= link_to edit_contrat_path(contrat) do %>
              <%= fa_stacked_icon "pencil inverse", base: "circle", class: "edit fa-1x" %>
            <% end %>

            <%= link_to contrat, method: :delete, data: { confirm: 'Voulez-vous vraiment supprimer cet élément?' } do %>
              <%= fa_stacked_icon "trash inverse", base: "circle", class: "delete fa-1x" %>
            <% end %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


  <%= link_to new_contrat_path, class: 'btn btn-primary' do %>
    <%= fa_icon 'plus' %> Nouveau contrat
  <% end %>
</div>

app/views/contrats/new.html.erb
<% content_for :page_title do %>
  Nouveau contrat
<% end %>

<%# content_for :box_width, "col-md-6" %>


<%= render 'form' %>

app/views/contrats/print_visites.html.erb
<% content_for :box_width, "col-md-12" %>

<pre><%= @contrat.visite_of_a_month(1) %></pre>