config/routes.rb
Rails.application.routes.draw do

  root 'dashboards#visites_preventive'

  get 'dashboards/tableau_board'
  get 'dashboards/visites_preventive'

  resources :intervenants
  resources :clients
  resources :type_contrats
  resources :qualites
  resources :regions
  resources :specialites

  devise_for :users, :controllers => { registrations: 'registrations' },
      :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  get 'print_contrats' => 'contrats#print_contrats'
  get 'print_visites' => 'contrats#print_visites'
  get 'apercu' => 'contrats#apercu'

  resources :contrats do
    collection {
      post :update_main_oeuvre
      post :update_piece_rechange
    }
    resources :visites
    get 'index2' => 'visites#index2'
  end

end

app/models/qualite.rb
class Qualite < ActiveRecord::Base
  default_scope -> { order(nom: :asc) }
end

app/controllers/qualites_controller.rb
class QualitesController < ApplicationController
  before_action :set_qualite, only: [:show, :edit, :update, :destroy]

  # GET /qualites
  # GET /qualites.json
  def index
    @qualites = Qualite.all
  end

  # GET /qualites/1
  # GET /qualites/1.json
  def show
  end

  # GET /qualites/new
  def new
    @qualite = Qualite.new
  end

  # GET /qualites/1/edit
  def edit
  end

  # POST /qualites
  # POST /qualites.json
  def create
    @qualite = Qualite.new(qualite_params)

    respond_to do |format|
      if @qualite.save
        format.html { redirect_to qualites_url, notice: 'Qualite a été créé avec succès.' }
        format.json { render :show, status: :created, location: @qualite }
      else
        format.html { render :new }
        format.json { render json: @qualite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualites/1
  # PATCH/PUT /qualites/1.json
  def update
    respond_to do |format|
      if @qualite.update(qualite_params)
        format.html { redirect_to qualites_url, notice: 'Qualite  a été mis à jour avec succès.' }
        format.json { render :show, status: :ok, location: @qualite }
      else
        format.html { render :edit }
        format.json { render json: @qualite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualites/1
  # DELETE /qualites/1.json
  def destroy
    @qualite.destroy
    respond_to do |format|
      format.html { redirect_to qualites_url, notice: 'Qualite a été supprimée avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualite
      @qualite = Qualite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qualite_params
      params.require(:qualite).permit(:nom)
    end
end

app/views/qualites/_form.html.erb
<!-- /.box-header -->
<%= form_for(@qualite,:html => { :class => 'from-inline'}) do |f| %>
  <% if @qualite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualite.errors.count, "error") %> prohibited this qualite from being saved:</h2>

      <ul>
        <% @qualite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="box-body">
    <div class="row">
      <div class="form-group">
        <%= f.label :nom, class: 'col-sm-2 control-label required' %>
        <div class="col-sm-10">
          <%= f.text_field :nom, :class => 'form-control', placeholder: :nom, :required => true%>
        </div>
      </div>
    </div>
  </div>

  <div class="box-footer">
    <button type="submit" class="btn btn-primary pull-right">
      <i class="fa fa-floppy-o" aria-hidden="true"></i> Valider
    </button>
    <a href="<%= qualites_url %>" class="btn btn-default pull-right">
      <i class="fa fa-times" aria-hidden="true"></i> Annuler
    </a>
  </div>
<% end %>

app/views/qualites/edit.html.erb
<% content_for :page_title do %>
  Edition Qualité
<% end %>

<%= render 'form' %>

app/views/qualites/index.html.erb
<% content_for :page_title do %>
  Liste Qualité
<% end %>

<div class="box-body">
  <table class="sortable datatable table table-hover table-condensed table-striped">
    <thead>
      <tr>
        <th>Nom</th>
        <td class="actions no-sort"></td>
      </tr>
    </thead>

    <tbody>
      <% @qualites.each do |qualite| %>
        <tr>
          <td><%= qualite.nom %></td>
          <td class="actions">
            <%= link_to edit_qualite_path(qualite) do %>
              <%= fa_stacked_icon "pencil inverse", base: "circle", class: "edit fa-1x" %>
            <% end %>

            <%= link_to qualite, method: :delete, data: { confirm: 'Voulez-vous vraiment supprimer cet élément?' } do %>
              <%= fa_stacked_icon "trash inverse", base: "circle", class: "delete fa-1x" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


  <%= link_to new_qualite_path, class: 'btn btn-primary' do %>
    <%= fa_icon 'plus' %> Nouvelle Qualité
  <% end %>
</div>

app/views/qualites/new.html.erb
<% content_for :page_title do %>
  Nouvelle Qualité
<% end %>

<%# content_for :box_width, "col-md-6" %>


<%= render 'form' %>