config/routes.rb
Rails.application.routes.draw do

  root 'dashboards#visites_preventive'

  get 'dashboards/tableau_board'
  get 'dashboards/visites_preventive'

  resources :intervenants
  resources :clients
  resources :type_contrats
  resources :qualites
  resources :regions
  resources :specialites

  devise_for :users, :controllers => { registrations: 'registrations' },
      :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'}

  get 'print_contrats' => 'contrats#print_contrats'
  get 'print_visites' => 'contrats#print_visites'
  get 'apercu' => 'contrats#apercu'

  resources :contrats do
    collection {
      post :update_main_oeuvre
      post :update_piece_rechange
    }
    resources :visites
    get 'index2' => 'visites#index2'
  end

end

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">G<b>CR</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">Gestion<b>Contrats</b></span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
        <!--<li class="dropdown messages-menu">-->
          <!--&lt;!&ndash; Menu toggle button &ndash;&gt;-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
            <!--<i class="fa fa-envelope-o"></i>-->
            <!--<span class="label label-success">4</span>-->
          <!--</a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li class="header">You have 4 messages</li>-->
            <!--<li>-->
              <!--&lt;!&ndash; inner menu: contains the messages &ndash;&gt;-->
              <!--<ul class="menu">-->
                <!--<li>&lt;!&ndash; start message &ndash;&gt;-->
                  <!--<a href="#">-->
                    <!--<div class="pull-left">-->
                      <!--&lt;!&ndash; User Image &ndash;&gt;-->
                      <!--<%#= image_tag "user-women160x160.png", :class => "img-circle", :alt => "User Image" %>-->

                    <!--</div>-->
                    <!--&lt;!&ndash; Message title and timestamp &ndash;&gt;-->
                    <!--<h4>-->
                      <!--Support Team-->
                      <!--<small><i class="fa fa-clock-o"></i> 5 mins</small>-->
                    <!--</h4>-->
                    <!--&lt;!&ndash; The message &ndash;&gt;-->
                    <!--<p>Why not buy a new awesome theme?</p>-->
                  <!--</a>-->
                <!--</li>&lt;!&ndash; end message &ndash;&gt;-->
              <!--</ul>&lt;!&ndash; /.menu &ndash;&gt;-->
            <!--</li>-->
            <!--<li class="footer"><a href="#">See All Messages</a></li>-->
          <!--</ul>-->
        <!--</li>&lt;!&ndash; /.messages-menu &ndash;&gt;-->

        <!-- Notifications Menu -->
        <li class="dropdown notifications-menu">
          <!-- Menu toggle button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning"><%= @notification_count %></span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">Vous avez <%= @notification_count %> notifications</li>
            <li>
              <!-- Inner Menu: contains the notifications -->
              <ul class="menu">
                <!-- start notification -->
                <% if @not1_visites_by_today.count > 0 %>
                  <li>
                    <%= link_to root_path do %>
                      <i class="fa fa-calendar-check-o orange"></i> <%= @not1_visites_by_today.count %> Visites planifier pour aujourd'huit
                    <% end %>
                  </li>
                <% end %>
                <% if @not1_visites_by_this_month.count > 0 %>
                  <li>
                    <%= link_to root_path do %>
                      <i class="fa fa-calendar blue"></i> <%= @not1_visites_by_this_month.count %> Visites planifier pour ce mois
                    <% end %>
                  </li>
                <% end %>
                <% if @not1_terminate_5_weeks_from_now.count > 0 %>
                  <% @not1_terminate_5_weeks_from_now.each do |contrat| %>
                  <li>
                    <%= link_to edit_contrat_path(contrat) do %>
                      <i class="fa fa-exclamation-triangle red"></i> <%= contrat.numero %> Prendra fin bientôt
                    <% end %>
                  </li>
                  <% end %>
                <% end %>
                <!-- end notification -->
              </ul>
            </li>
            <li class="footer"><a href="#">Afficher tout</a></li>
          </ul>
        </li>

        <!-- Tasks Menu -->
        <!--<li class="dropdown tasks-menu">-->
          <!--&lt;!&ndash; Menu Toggle Button &ndash;&gt;-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
            <!--<i class="fa fa-flag-o"></i>-->
            <!--<span class="label label-danger">9</span>-->
          <!--</a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li class="header">You have 9 tasks</li>-->
            <!--<li>-->
              <!--&lt;!&ndash; Inner menu: contains the tasks &ndash;&gt;-->
              <!--<ul class="menu">-->
                <!--<li>&lt;!&ndash; Task item &ndash;&gt;-->
                  <!--<a href="#">-->
                    <!--&lt;!&ndash; Task title and progress text &ndash;&gt;-->
                    <!--<h3>-->
                      <!--Design some buttons-->
                      <!--<small class="pull-right">20%</small>-->
                    <!--</h3>-->
                    <!--&lt;!&ndash; The progress bar &ndash;&gt;-->
                    <!--<div class="progress xs">-->
                      <!--&lt;!&ndash; Change the css width attribute to simulate progress &ndash;&gt;-->
                      <!--<div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">-->
                        <!--<span class="sr-only">20% Complete</span>-->
                      <!--</div>-->
                    <!--</div>-->
                  <!--</a>-->
                <!--</li>&lt;!&ndash; end task item &ndash;&gt;-->
              <!--</ul>-->
            <!--</li>-->
            <!--<li class="footer">-->
              <!--<a href="#">View all tasks</a>-->
            <!--</li>-->
          <!--</ul>-->
        <!--</li>-->
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag "user-women160x160.png", :class => "user-image", :alt => "User Image" %>
            <span class="hidden-xs"><%= current_user.nom if current_user %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <%= image_tag "user-women160x160.png", :class => "img-circle", :alt => "User Image" %>

              <p>
                <%= current_user.nom if current_user %> <br> Relation Clientèle
                <small>Expérience 2 ans</small>
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <%= link_to "Profil", edit_user_registration_path, :class => 'btn btn-default btn-flat' %>
              </div>
              <div class="pull-right">
                <%= link_to destroy_user_session_path, :method => :delete, :class => 'btn btn-default btn-flat disconnect' do %>
                  <%= fa_icon "power-off" %> Se Déconnecter
                <% end %>
              </div>
            </li>
          </ul>
        </li>
        <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-print"></i></a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "user-women160x160.png", :class => "img-circle", :alt => "User Image" %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.nom if current_user %></p>
        <!-- Status -->
        <a href="#"><i class="fa fa-circle text-success"></i> En Ligne</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">MENU PRINCIPAL</li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-dashboard"></i>
          <span>Tableaux de bord</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul style="display: none;" class="treeview-menu">

          <%= active_link_to dashboards_tableau_board_path, :wrap_tag => :li do %>
            <%= fa_icon "circle-o" %> <span>Général</span>
          <% end %>
          <%#= active_link_to dashboards_visites_preventive_path, :wrap_tag => :li do %>
          <%= active_link_to root_path, :wrap_tag => :li, :active => :exclusive do %>
            <%= fa_icon "calendar-check-o" %> <span>Visites Préventive</span>
          <% end %>

          <%= active_link_to apercu_path, :wrap_tag => :li do %>
            <%= fa_icon "file-text-o" %> <span>Liste Contrats</span>
          <% end %>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-gears"></i>
          <span>Paramétrage</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul style="display: none;" class="treeview-menu">

          <%= active_link_to contrats_path, :wrap_tag => :li do %>
            <%= fa_icon "circle-o" %> <span>Contrats</span>
          <% end %>

          <%= active_link_to clients_path, :wrap_tag => :li do %>
            <%= fa_icon "circle-o" %> <span>Clients</span>
          <% end %>

          <%= active_link_to intervenants_path, :wrap_tag => :li do %>
            <%= fa_icon "circle-o" %> <span>Intervenants</span>
          <% end %>

          <%= active_link_to regions_path, :wrap_tag => :li do %>
            <%= fa_icon "circle-o" %> <span>Régions</span>
          <% end %>

          <%= active_link_to qualites_path, :wrap_tag => :li do %>
            <%= fa_icon "circle-o" %> <span>Qualités</span>
          <% end %>

          <%= active_link_to specialites_path, :wrap_tag => :li do %>
            <%= fa_icon "circle-o" %> <span>Spécialités</span>
          <% end %>
          <%= active_link_to type_contrats_path, :wrap_tag => :li do %>
            <%= fa_icon "circle-o" %> <span>Types Contrat</span>
          <% end %>
        </ul>
      </li>
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>
    <% if content_for?(:page_title) %>
      <%= yield :page_title %> | GestionContrat
    <% else %>
      Gestion Contrat
    <% end %>
  </title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body class="skin-black sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <%= render partial: 'layouts/admin_lte_2_header' %>

    <%= render partial: 'layouts/admin_lte_2_sidebar' %>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          <%= yield :page_title %>
          <small></small>
        </h1>
        <!--<ol class="breadcrumb">-->
          <!--<li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>-->
          <!--<li class="active">Here</li>-->
        <!--</ol>-->
      </section>

      <!-- Main content -->
      <section class="content">


        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <div class="row">
          <div class=<%= set_box_width %>>
            <div class="box box-primary">
              <%= yield %>
            </div>
          </div>
          <%= render :partial => 'shared/right_sidebar' %>
        </div>
      </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- To the right -->
      <div class="pull-right hidden-xs">
        <b><%= (l Time.now, format: :long).to_s.capitalize %> </b>
      </div>
      <!-- Default to the left -->
      <strong>Copyright &copy; 2016 <a href="http://www.dyna-info.com/" target="_blank">Dyna Info</a>.</strong> Tous les droits sont réservés.
    </footer>

    <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li class="active"><a href="#control-sidebar-print-tab" data-toggle="tab" aria-expanded="true"><i class="fa fa-print"></i></a></li>
          <li class=""><a href="#control-sidebar-settings-tab" data-toggle="tab" aria-expanded="false"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <!-- Home tab content -->
          <div class="tab-pane active" id="control-sidebar-print-tab">
            <h3 class="control-sidebar-heading"><b>Zone Impression</b></h3>
            <!--<ul class="control-sidebar-menu">-->
              <!--<li>-->
                <!--<a href="javascript::;">-->
                  <!--<i class="menu-icon fa fa-birthday-cake bg-red"></i>-->
                  <!--<div class="menu-info">-->
                    <!--<h4 class="control-sidebar-subheading">Langdon's Birthday</h4>-->
                    <!--<p>Will be 23 on April 24th</p>-->
                  <!--</div>-->
                <!--</a>-->
              <!--</li>-->
            <!--</ul>&lt;!&ndash; /.control-sidebar-menu &ndash;&gt;-->

            <!--<h3 class="control-sidebar-heading">Impression</h3>-->
            <ul class="control-sidebar-menu">
              <li>
                <%= active_link_to apercu_path do %>
                  <h4 class="control-sidebar-subheading">
                    <%= fa_icon 'eye' %> Aperçu Contrats
                  </h4>
                  <!--<div class="progress progress-xxs">-->
                  <!--<div class="progress-bar progress-bar-danger" style="width: 70%"></div>-->
                  <!--</div>-->
                <% end %>
              </li>
              <li>
                <%= active_link_to print_contrats_path(format: 'pdf'), target: "_blank" do %>
                  <h4 class="control-sidebar-subheading">
                    <%= fa_icon 'print' %> Impression Contrats
                  </h4>
                  <!--<div class="progress progress-xxs">-->
                  <!--<div class="progress-bar progress-bar-danger" style="width: 70%"></div>-->
                  <!--</div>-->
                <% end %>
              </li>
              <li>
                <%= active_link_to print_visites_path(format: 'pdf'), target: "_blank" do %>
                  <h4 class="control-sidebar-subheading">
                    <%= fa_icon 'calendar' %> Impression Visites
                  </h4>
                  <!--<div class="progress progress-xxs">-->
                  <!--<div class="progress-bar progress-bar-danger" style="width: 70%"></div>-->
                  <!--</div>-->
                <% end %>
              </li>
            </ul><!-- /.control-sidebar-menu -->

          </div><!-- /.tab-pane -->
          <!-- Stats tab content -->
          <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
          <!-- Settings tab content -->
          <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
              <h3 class="control-sidebar-heading">Paramètres Général</h3>
              <div class="form-group">
                <label class="control-sidebar-subheading">
                  <!--Report panel usage-->
                  <!--<input type="checkbox" class="pull-right" checked="">-->
                </label>
                <p>
                  ...
                </p>
              </div><!-- /.form-group -->
            </form>
          </div><!-- /.tab-pane -->
        </div>
      </aside>

      <div class="control-sidebar-bg" style="position: fixed; height: auto;"></div>

  </div><!-- ./wrapper -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<% if notice %>
  <!--<div class="alert alert-success alert-dismissable">-->
  <!--<i class="fa fa-check"></i>-->
  <!--<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>-->
  <!--<b><%#= notice %></b>-->
  <!--</div>-->

  <script type="text/javascript">
    toastr.success('<%= notice %>')
  </script>
<% end %>


</body>
</html>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Log In | GestionContrats</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/">Gestion<b>Contrat</b></a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Connectez-vous pour commencer votre session</p>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-group has-feedback">
        <%= f.text_field :email, class: 'form-control', autofocus: true, placeholder: 'Email' %>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off', placeholder: 'Mot de passe' %>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="d">
            <label>
              <input type="checkbox" class='icheck' data-skin="square" data-color="blue"> Rester Connecté
            </label>
          </div>
        </div><!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit 'Log in', class: 'btn btn-primary btn-block btn-flat' %>
        </div><!-- /.col -->
      </div>
      <div class="row">
        <div class="col-xs-8">
          <%= link_to 'Inscrivez-vous', new_user_registration_path %>
        </div>
      </div>

    <% end %>
  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<% if devise_error_messages! != '' %>
  <script type="text/javascript">
    toastr.error('<%= raw devise_error_messages!.squish %>');
  </script>
<% end %>
<% if alert %>
  <script type="text/javascript">
    toastr.warning('<%= alert %>');
  </script>
<% end %>
</body>
</html>

app/views/layouts/admin_lte_2_register.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Inscription | GestionContrats</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/">Gestion<b>Contrat</b></a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Inscrivez-vous pour commencer votre session</p>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <div class="form-group has-feedback">
      <%= f.text_field :nom, class: 'form-control', autofocus: true, placeholder: 'Nom Complet' %>
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>

    <div class="form-group has-feedback">
      <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>

        <div class="form-group has-feedback">
          <%= f.password_field :password, class: 'form-control', autocomplete: 'off', placeholder: 'Mot de passe' %>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>

            <div class="form-group has-feedback">
              <%= f.password_field :password_confirmation, class: 'form-control', autocomplete: 'off', placeholder: 'Confirmation du mot de passe ' %>
                <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
                <div class="row">

                  <div class="col-xs-8">
                    <%= link_to 'Se Connecter', new_user_session_path %>
                  </div>
                  <div class="col-xs-4">
                    <%= f.submit 'Souscrire', class: 'btn btn-primary btn-block btn-flat' %>
                      </div><!-- /.col -->
                      </div>
                    <% end %>
                    </div><!-- /.login-box-body -->
                    </div><!-- /.login-box -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<% if devise_error_messages! != '' %>
<script type="text/javascript">
  toastr.error('<%= raw devise_error_messages!.squish %>');
</script>
<% end %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GestionContrats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>